version: '3.12'

services:
  postgres:
    image: postgres:16.0
    init: true
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - base_postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13.2-management
    init: true
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - base_rabbitmq_data:/var/lib/rabbitmq/
      - base_rabbitmq_log:/var/log/rabbitmq

  redis:
    image: redis:7.2.5
    init: true
    hostname: redis
    command: redis-server
    ports:
      - 6379:6379

  api:
    build: .
    init: true
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - rabbitmq
      - redis
    environment:
      - ENV=local
      - DEBUG=1
      - POSTGRES__DSN=postgresql://postgres@postgres/postgres
      - BROKER__URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS__HOST=default@redis:6379/0

volumes:
  base_postgres:
  base_rabbitmq_data:
  base_rabbitmq_log:
